CREATE TABLE [dbo].[Departments]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[DepartmentName] NVARCHAR(100) NOT NULL, 
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[IsActive] BIT NOT NULL DEFAULT 1
)
