CREATE TABLE [dbo].[Employees]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[Email] NVARCHAR(255)  NOT NULL, 
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [UserId] NVARCHAR(500) NOT NULL,
)
