CREATE TABLE [dbo].[Stations]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[StationName] NVARCHAR(100) NOT NULL, 
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[IsActive] BIT NOT NULL DEFAULT 1
)
